---
abstract: 'Localizable, inheritable, overridable class data'
author:
  - 'Sebastian Knapp <sk@computer-leipzig.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Data-Localize
provides:
  Class::Data::Localize:
    file: lib/Class/Data/Localize.pm
    version: 0.04
requires:
  ReleaseAction: 0.07
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
